### ISSUE TITLE
Could not resolve com.datastax.dse:dse-db:6.8.23

### ISSUE THREAD

**Issue by xiaodizi** [datastax/cdc-apache-cassandra#125]
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/10411525/226851150-4fd9226d-3217-471b-b0ce-3e30003fedfc.png">

Is this a charge bag? Unable to download

**Comment by aymkhalil** [comment]
> Is this a charge bag?
No. That is not the intension. The CLI tool that is failing on you is not yet released and will be vended as an artifact on the release page. In the meantime, I'll take a look what can be done to enable a successful build for all users.
