### ISSUE TITLE
Collection support in CDC.

### ISSUE THREAD

**Issue by continuum-jayvin-shah** [datastax/cdc-apache-cassandra#43]
I have tried few functionality on CDC and found that Column with collections type like List, Set, Maps are not getting synced to Elastic Search. @vroyer @jgillenwater @kijanowski @eolivelli

**Comment by eolivelli** [comment]
There is an open PR
https://github.com/datastax/cdc-apache-cassandra/pull/48

we should cut a release next week with this feature

**Comment by continuum-jayvin-shah** [comment]
> There is an open PR #48
> 
> we should cut a release next week with this feature
HI @eolivelli ,

We tried testing with branch mentioned in PR but It didn't work as expected for collection type. Can you help us understand If we are missing something. Collection data not getting mapped to elastic search.

**Comment by continuum-jayvin-shah** [comment]
@eolivelli @olim7t , Can you please help me make CDC working with Collection Type. I tried but It's not working as Expected. 

If you can provide some steps to make it work, That would be helpful.
