### ISSUE TITLE
Read CDC agent configuration from a file

### ISSUE THREAD

**Issue by yabinmeng** [datastax/cdc-apache-cassandra#45]
When a CDC agent connects to Pulsar cluster, it needs to provide certain configuration parameters  such as the connection URL, security token, TLS encryption certificate, etc. Right now, all these parameters are provided directly as part of the JVM options. This is not flexible and it is better to read these configuration settings from a configuration file.

This is especially needed for K8s based authentication because most likely the security related configuration parameters (e.g. tokens, certificates, etc.) are provided as K8s secrets.

**Comment by cdbartholomew** [comment]
This has been resolved by using environment variables in this commit: https://github.com/datastax/cdc-apache-cassandra/commit/9824c5cb73c8ed021d763c18e344ed70b9524b7a
