### ISSUE TITLE
Support for JSON message format

### ISSUE THREAD

**Issue by rakulkar-tibco** [datastax/cdc-apache-cassandra#99]
Does it support JSON message format?
If yes, is there any documentation?

**Comment by rakulkar-tibco** [comment]
Found outputFormat source cofiguration.

**Comment by aymkhalil** [comment]
Here is the public docs too on JSON format: https://docs.datastax.com/en/cdc-for-cassandra/docs/2.2.2/cdcExample.html#_deploy_pulsar_connector
